services:
  bkipay-be:
    image: bkipay-be:v1
    container_name: bkipay-be
    hostname: bkipay-be
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "8010:8010"
      - "8011:443" 
    env_file:
      - stack.env
    # volumes:
      # - type: bind
        # source: /mnt/data/source-code/development/bkipay-be
        # target: /app
    networks:
      - gcloud-apps-net
      - gcloud-dbs-net 
    healthcheck:
      test: curl --fail http://localhost:8010/api/hello || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
# Docker Networks
networks:
  gcloud-apps-net:
    name: gcloud-apps-net
    external: true
  gcloud-dbs-net:
    external: true